Created some dtos
FaceAnalyzer/backend pull request #16
Opened 2023-11-02 18:55 UTC by Mario2414

2023-11-03 18:16 UTC, TA50 commented on FaceAnalyzer.Api/Business/Contracts/EmotionDto.cs
Remove the Reaction entity navigation.
ReactionID => ReactionId

2023-11-03 18:25 UTC, TA50 requested changes

2023-11-03 18:25 UTC, TA50 commented on FaceAnalyzer.Api/Business/Contracts/ReactionDto.cs
Remove Emotiin entity collection
Remove Stimuli entity
Typo in ParticipantName

2023-11-03 18:25 UTC, TA50 commented on FaceAnalyzer.Api/Business/Contracts/StimuliDto.cs
Remove reactions
Remove experiment

2023-11-03 18:25 UTC, TA50 commented on FaceAnalyzer.Api/Service/Contracts/CreateEmotionDto.cs
Remove Id  and Reaction Entity

2023-11-03 18:25 UTC, TA50 commented on FaceAnalyzer.Api/Service/Contracts/CreateExperimentDto.cs
Remove Id

2023-11-03 18:25 UTC, TA50 commented on FaceAnalyzer.Api/Service/Contracts/CreateReactionDto.cs
Keep only StimuliId and ParticipantName

2023-11-03 18:25 UTC, TA50 commented on FaceAnalyzer.Api/Service/Contracts/CreateStimuliDto.cs
Remove entities
Experiment and Reactions

2023-11-04 13:45 UTC, Mario2414 commented
Pushed the new commit, check if it's ok

2023-11-04 14:36 UTC, TA50 approved these changes

2023-11-04 14:36 UTC, merged