Class digrams
FaceAnalyzer/backend pull request #74
Opened 2023-12-15 19:29 UTC by de7miii

- Add PlantUML class diagrams.

2023-12-17 14:13 UTC, plavy requested changes
@de7miii  Do you know why is CodeQL failing? It seems like the project can't be built. Can you build it locally?

2023-12-18 17:27 UTC, de7miii commented
@plavy It's building fine locally and I also didn't alter any files on the project, I only added the class diagrams files which shouldn't affect the build.

2023-12-19 13:27 UTC, Mario2414 approved these changes

2023-12-19 14:54 UTC, plavy commented
@TA50 @de7miii The same check passes on both develop and main, please investigate.

2023-12-20 17:08 UTC, TA50 approved these changes

2023-12-20 17:12 UTC, plavy approved these changes

2023-12-20 19:07 UTC, merged